name: Snyk Java + Docker Scan

on:
  push:
    branches:
      - main
      - test
  pull_request:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java app
        run: mvn clean install -DskipTests

      - name: Snyk Open Source scan
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      - name: Build Docker image
        run: docker build -t my-java-app .

      - name: Snyk Container scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: my-java-app
          args: --file=Dockerfile

      - name: Upload to Snyk dashboard
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk monitor
